baseURL: https://lbs-blockchain.com/
languageCode: en-us
title: LBS Blockchain
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Bringing together bright minds to shape the development of the internet of value, the Web 3.0
    title: Welcome to the LBS Blockchain Society
  blog: {}
  contact:
    address:
      - city: London, NW1 6BU
        country: United Kingdom
        street: Sussex Place
        title: Address
    buttonClear: Clear
    buttonSend: Get in touch
    email:
      - email: lbsblockchain@protonmail.com
        title: Email
    enable: yes
    # phone:
    #   - phone: https://t.me/joinchat/TmY0VjZsnlcxM2Yy
    #     title: Telegram
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: LBS Blockchain
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/lbsblockchain
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      # - icon: fa-github
      #   label: GitHub
      #   url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/company/lbs-blockchain-club/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Home
        url: '#'
    button2:
      - name: Twitter
        url: https://www.twitter.com/lbsblockchain
    button3:
      - name: Telegram
        url: https://t.me/joinchat/TmY0VjZsnlcxM2Yy
    button4:
      - name: Medium
        url: https://medium.com/@lbsblockchain
    links:
      # - name: Home
      #   url: '#'
      # - name: Blogs
      #   url: blogs
      # - name: Generic Blog
      #   url: blogs/ipsum
      # - name: Elements
      #   url: elements.html
    menu: Menu
    subtitle: "."
    title: LBS Blockchain 
  tiles:
    enable: yes
    showcase:
      - image: events.jpg
        subtitle: Learn more about Bitcoin, Cryptocurrencies and more
        title: Events
        url: blogs/events
      - image: crypto.jpg
        subtitle: In depth research on the market and the technology 
        title: Research
        url: blogs/research
      - image: trading.jpg
        subtitle: Work in progress
        title: Trading
        url: blogs/trading
      - image: digital.jpg
        subtitle: DAO's, NFTs, Smartcontracts and more
        title: Technology Labs
        url: blogs/technology
      - image: partners.jpg
        subtitle: Connecting the dots to achieve decentralization
        title: Industry Partners
        url: blogs/partners
      - image: team.jpg
        subtitle: The Builders, Hodlers and Enthusiasts
        title: About us
        url: blogs/about-us
  two:
    buttonText: connect with us
    enable: yes
    subtitle: "We want to foster a community at LBS to make blockchain approachable, understandable and prepare our peers for the opportunities of the Web 3.0  \r\n "
    title: Our mission
    url: https://twitter.com/lbsblockchain
