---
title: "Events"
date: '2017-10-31T21:28:43-05:00'
description: ''
draft: no
image: null
keywords: ''
slug: events
categories:
- ''
- ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 🚀 Workshop Alert 🚀 ✨

## LBS Blockchain Association x LBS TMC present: "Into the Hyperverse," a Web 3.0 Workshop hosted by Decentology

🗓 Date & Time: Thursday, February 17 @ 5 PM (location TBC)
‼️ Application Deadline: Sunday, February 6 (details on Eventbrite) 
📲 [Registration Link](https://www.eventbrite.co.uk/e/into-the-hyperverse-a-web-30-workshop-tickets-256817908277)

**ABOUT THE EVENT**

“Into the Hyperverse" is a session for individuals interested in a Web 3.0 career presented by Nik Kalyani and Samina Kabir of Decentology, a Silicon Valley-based crypto company.

In this session, Kalyani and Kabir will start by introducing you to crypto fundamentals of web architecture, blockchain, cryptography, smart contracts, and decentralized applications ("dapps").

Next, you'll get a glimpse into the future of composable dapps by journeying into the Hyperverse, an open marketplace for "smart modules," which are like Lego blocks for building dapps.

Finally, Kalyani and Kabir will round it out by building a simple dapp LIVE, that'll give you deep insights into how dapps work and what skills you'll need to build for the Hyperverse.

Join us in this exciting session bringing nothing other than a great attitude, and a desire to immerse yourself into the exciting new world of crypto. You'll leave invigorated with all the knowledge you need to venture into the Hyperverse ✨

_Please note: this event is open to the LBS community only. We thank you, in advance, for your understanding. Additionally, all LBS students are encouraged to apply; however, priority will be given to those with prior coding experience and/ or background in math and computer science._


## 🚀 Employer Presentation & Networking Session 🚀 

## Interested in a career in blockchain? Come hear from TriliTech on February 14th ✨

Date & Time: Monday, February 14th @ 11:15 AM
[Register here](https://london-csm.symplicity.com/students/?s=event&ss=is&mode=form&id=ab14bc07d7cde0030f1d5e6e6ecb047e) 

**ABOUT TRILITECH**
 
TriliTech is a Tezos blockchain R&D and Entrepreneur Hub based in London, UK. Its objective is to further develop and catalyse unique opportunities for the Tezos ecosystem, both on and off-chain. TriliTech is building a business development & adoption team to lead global promotion of the Tezos blockchain, a leading layer 1 protocol launched in 2018. 
Tezos is an open-source platform that addresses key barriers facing blockchain adoptions backed by a global community of validators, researchers and builders. Our current corporate partners include Redbull Racing, McLaren, Ubisoft, Societe Generale and many others.


## Upcoming Events:

Our Events team will cover the following topics this academic year. Details TBA

### 1. Blockchain 101 series


An introduction to bitcoin, ethereum and the technology underpinning them.


### 2. Smart Contracts and DApps


Learn about the power of smart contracts and the decentralized applications they enable.


### 3. Web 3.0


From the internet of user generated content (Web 2.0), to the internet of value (web 3.0). Where do we go from here?

### 4. NFT workshops


Learn more about Non-Fungible-Tokens in our dedicated workshop series.

### 5. DAOs


Learn more about the new way of collaborating through decentralized autonomous organisations. 



Follow us on our social media to stay up to date with our events..

**Contact us:**

Kat Fore, Senior Head of Events, kfore.mba2022@london.edu

Pushpendra Dwivedi, Junior Head of Events, pdwivedi.embals2023@london.edu


